language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./script/cibuild.sh # or do this locally and commit
 - chmod +x ./script/test.rb # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  except:
  - master     # the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  local-dir: _site
  fqdn: blog.staticvoid.co.nz
  on:
    branch: develop